spring:
  application:
    name: Hello-Eureka-Client
    
server:
  port: 8484
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka/} 
      
  instance:
    prefer-ip-address: true